#! /usr/bin/env bash

set -e # Exit on errors
set +x # Shows the output of every command

home() {
  home-manager switch
}
update() {
  fish -c fish_update_completions
  sudo nix-channel --update
  nix flake update ~/nixos-config/machines/mystique
}
system() {
  sudo nixos-rebuild switch --flake ~/nixos-config/
}
restartdm() {
  echo "⚠️ Restarting X11 (requires authentication) ⚠️"
  systemctl restart display-manager
}
case $1 in
  "home")
    home $2;;
  "restartdm")
    restartdm;;
  "system")
    system;;
  "update")
    update;;
  *)
    echo "expected 'home', 'restartdm', 'system'";;
esac
